In [1]:
import pandas as pd
import datetime
csv = pd.read_csv('CleanData.csv')

In [2]:
optionData = csv.loc[:,['currentDate', 'ExpDate', 'StrikePrice', 'Ticker', 'Type', 'Last', 'IV']]

for d in set(optionData.ExpDate):
    optionData.ix[optionData.ExpDate == d, 'ExpDate'] = datetime.datetime.strptime(d, '%b %d, %Y').date()

for d2 in set(optionData.currentDate):
    optionData.ix[optionData.currentDate == d2, 'currentDate'] = datetime.datetime.strptime(d2, '%Y-%m-%d').date()
        

optionData.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>currentDate</th>
      <th>ExpDate</th>
      <th>StrikePrice</th>
      <th>Ticker</th>
      <th>Type</th>
      <th>Last</th>
      <th>IV</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2017-02-17</td>
      <td>2017-07-21</td>
      <td>34.799999</td>
      <td>TBNK</td>
      <td>Call</td>
      <td>1.06</td>
      <td>0.13250</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2017-02-17</td>
      <td>2017-02-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>1.65</td>
      <td>0.13250</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2017-02-17</td>
      <td>2017-02-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.06</td>
      <td>0.50777</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2017-02-17</td>
      <td>2017-02-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.08</td>
      <td>1.78007</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2017-02-17</td>
      <td>2017-02-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.90</td>
      <td>0.68446</td>
    </tr>
  </tbody>
</table>
</div>

In [3]:
from pandas_datareader import data as web
def getStockPrice(df):
    
    df2 = df.copy()
    
    for ticker in set(df.Ticker):   
        for date in set(df.loc[df.Ticker == ticker, 'currentDate']):
            try:
                f = web.DataReader(ticker, 'yahoo', start=date, end=date)
                df2.loc[(df.Ticker == ticker) & (df.currentDate == date), 'StockPrice'] = f.loc[date, 'Close']
            except:
                print(ticker)
                break
                

    return df2

getStockPrice(optionData.head(20))

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>currentDate</th>
      <th>ExpDate</th>
      <th>StrikePrice</th>
      <th>Ticker</th>
      <th>Type</th>
      <th>Last</th>
      <th>IV</th>
      <th>StockPrice</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2017-02-17</td>
      <td>2017-07-21</td>
      <td>34.799999</td>
      <td>TBNK</td>
      <td>Call</td>
      <td>1.06</td>
      <td>0.13250</td>
      <td>33.549999</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2017-02-17</td>
      <td>2017-02-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>1.65</td>
      <td>0.13250</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2017-02-17</td>
      <td>2017-02-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.06</td>
      <td>0.50777</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2017-02-17</td>
      <td>2017-02-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.08</td>
      <td>1.78007</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2017-02-17</td>
      <td>2017-02-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.90</td>
      <td>0.68446</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>1.70</td>
      <td>0.02022</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.08</td>
      <td>0.13956</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.20</td>
      <td>0.32783</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.95</td>
      <td>0.27590</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>1.25</td>
      <td>0.02022</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>10</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>21.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.75</td>
      <td>0.05176</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>11</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>22.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.30</td>
      <td>0.10719</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>12</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>23.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.11</td>
      <td>0.10208</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>13</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.15</td>
      <td>0.25595</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>14</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>21.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.50</td>
      <td>0.24133</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>15</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>22.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.83</td>
      <td>0.21858</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>16</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>23.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>1.55</td>
      <td>0.33344</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>17</th>
      <td>2017-02-17</td>
      <td>2017-07-21</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>1.60</td>
      <td>0.13250</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>18</th>
      <td>2017-02-17</td>
      <td>2017-07-21</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.40</td>
      <td>0.09176</td>
      <td>21.709999</td>
    </tr>
    <tr>
      <th>19</th>
      <td>2017-02-17</td>
      <td>2017-07-21</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.55</td>
      <td>0.28827</td>
      <td>21.709999</td>
    </tr>
  </tbody>
</table>
</div>

In [4]:
optionData = getStockPrice(optionData)

In [5]:
optionData.loc[:, 'T'] = ((optionData.loc[:, 'ExpDate'] - optionData.loc [:, 'currentDate']) / datetime.timedelta(days=1)).astype(float) / 365.25
optionData2 = optionData.loc[(optionData.loc[:, 'T'] > 0), :]
optionData2 = optionData2.reset_index(drop=True)

In [6]:
optionData2.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>currentDate</th>
      <th>ExpDate</th>
      <th>StrikePrice</th>
      <th>Ticker</th>
      <th>Type</th>
      <th>Last</th>
      <th>IV</th>
      <th>StockPrice</th>
      <th>T</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2017-02-17</td>
      <td>2017-07-21</td>
      <td>34.799999</td>
      <td>TBNK</td>
      <td>Call</td>
      <td>1.06</td>
      <td>0.13250</td>
      <td>33.549999</td>
      <td>0.421629</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>1.70</td>
      <td>0.02022</td>
      <td>21.709999</td>
      <td>0.076660</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.08</td>
      <td>0.13956</td>
      <td>21.709999</td>
      <td>0.076660</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.20</td>
      <td>0.32783</td>
      <td>21.709999</td>
      <td>0.076660</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.95</td>
      <td>0.27590</td>
      <td>21.709999</td>
      <td>0.076660</td>
    </tr>
  </tbody>
</table>
</div>

In [7]:
from ImpliedVolatility import ImpliedVolatility as iv
sigma0 = 0.5
r = 0.005

df = optionData2
dfCopy = df.copy()
for i in df.index:
    dfCopy.ix[i, 'ImpliedVolatility'] = iv(df.ix[i, 'StockPrice'], df.ix[i, 'StrikePrice'], df.ix[i, 'T'], r, sigma0, df.ix[i, 'Last'], df.ix[i, 'Type']).bsmBisectionVol()

dfCopy.head(10)

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>currentDate</th>
      <th>ExpDate</th>
      <th>StrikePrice</th>
      <th>Ticker</th>
      <th>Type</th>
      <th>Last</th>
      <th>IV</th>
      <th>StockPrice</th>
      <th>T</th>
      <th>ImpliedVolatility</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2017-02-17</td>
      <td>2017-07-21</td>
      <td>34.799999</td>
      <td>TBNK</td>
      <td>Call</td>
      <td>1.06</td>
      <td>0.13250</td>
      <td>33.549999</td>
      <td>0.421629</td>
      <td>0.178680</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>1.70</td>
      <td>0.02022</td>
      <td>21.709999</td>
      <td>0.076660</td>
      <td>10.000000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.08</td>
      <td>0.13956</td>
      <td>21.709999</td>
      <td>0.076660</td>
      <td>0.137428</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.20</td>
      <td>0.32783</td>
      <td>21.709999</td>
      <td>0.076660</td>
      <td>0.336280</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.95</td>
      <td>0.27590</td>
      <td>21.709999</td>
      <td>0.076660</td>
      <td>0.187211</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>1.25</td>
      <td>0.02022</td>
      <td>21.709999</td>
      <td>0.172485</td>
      <td>10.000000</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>21.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.75</td>
      <td>0.05176</td>
      <td>21.709999</td>
      <td>0.172485</td>
      <td>0.060732</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>22.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.30</td>
      <td>0.10719</td>
      <td>21.709999</td>
      <td>0.172485</td>
      <td>0.116530</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>23.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.11</td>
      <td>0.10208</td>
      <td>21.709999</td>
      <td>0.172485</td>
      <td>0.138773</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.15</td>
      <td>0.25595</td>
      <td>21.709999</td>
      <td>0.172485</td>
      <td>0.202566</td>
    </tr>
  </tbody>
</table>
</div>

In [8]:
import numpy as np
tolerance = 0.05

dfCopy.loc[:, 'Difference'] = dfCopy.IV - dfCopy.ImpliedVolatility
outputData = dfCopy.loc[np.fabs(dfCopy.Difference) < tolerance, :]
outputData.to_csv("europeanOptions_2.csv")
outputData.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>currentDate</th>
      <th>ExpDate</th>
      <th>StrikePrice</th>
      <th>Ticker</th>
      <th>Type</th>
      <th>Last</th>
      <th>IV</th>
      <th>StockPrice</th>
      <th>T</th>
      <th>ImpliedVolatility</th>
      <th>Difference</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2017-02-17</td>
      <td>2017-07-21</td>
      <td>34.799999</td>
      <td>TBNK</td>
      <td>Call</td>
      <td>1.06</td>
      <td>0.13250</td>
      <td>33.549999</td>
      <td>0.421629</td>
      <td>0.178680</td>
      <td>-0.046180</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>22.500000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.08</td>
      <td>0.13956</td>
      <td>21.709999</td>
      <td>0.076660</td>
      <td>0.137428</td>
      <td>0.002132</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>20.000000</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.20</td>
      <td>0.32783</td>
      <td>21.709999</td>
      <td>0.076660</td>
      <td>0.336280</td>
      <td>-0.008450</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>21.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.75</td>
      <td>0.05176</td>
      <td>21.709999</td>
      <td>0.172485</td>
      <td>0.060732</td>
      <td>-0.008972</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>22.000000</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.30</td>
      <td>0.10719</td>
      <td>21.709999</td>
      <td>0.172485</td>
      <td>0.116530</td>
      <td>-0.009340</td>
    </tr>
  </tbody>
</table>
</div>

In [9]:
tolerance = 0.01

dfCopy.loc[:, 'Difference'] = dfCopy.IV - dfCopy.ImpliedVolatility
outputData = dfCopy.loc[np.fabs(dfCopy.Difference) < tolerance, :]
outputData.to_csv("europeanOptions_.01tol.csv")
outputData.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>currentDate</th>
      <th>ExpDate</th>
      <th>StrikePrice</th>
      <th>Ticker</th>
      <th>Type</th>
      <th>Last</th>
      <th>IV</th>
      <th>StockPrice</th>
      <th>T</th>
      <th>ImpliedVolatility</th>
      <th>Difference</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>22.5</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.08</td>
      <td>0.13956</td>
      <td>21.709999</td>
      <td>0.076660</td>
      <td>0.137428</td>
      <td>0.002132</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>20.0</td>
      <td>ARR</td>
      <td>Put</td>
      <td>0.20</td>
      <td>0.32783</td>
      <td>21.709999</td>
      <td>0.076660</td>
      <td>0.336280</td>
      <td>-0.008450</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>21.0</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.75</td>
      <td>0.05176</td>
      <td>21.709999</td>
      <td>0.172485</td>
      <td>0.060732</td>
      <td>-0.008972</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2017-02-17</td>
      <td>2017-04-21</td>
      <td>22.0</td>
      <td>ARR</td>
      <td>Call</td>
      <td>0.30</td>
      <td>0.10719</td>
      <td>21.709999</td>
      <td>0.172485</td>
      <td>0.116530</td>
      <td>-0.009340</td>
    </tr>
    <tr>
      <th>43</th>
      <td>2017-02-17</td>
      <td>2017-03-17</td>
      <td>180.0</td>
      <td>MSG</td>
      <td>Put</td>
      <td>6.45</td>
      <td>0.18380</td>
      <td>175.300003</td>
      <td>0.076660</td>
      <td>0.187619</td>
      <td>-0.003819</td>
    </tr>
  </tbody>
</table>
</div>